DO $$
DECLARE
    MINHA_VARIAVEL INT;
BEGIN
    MINHA_VARIAVEL := 14;
	
	DROP TABLE IF EXISTS foo;
	
	CREATE TEMPORARY TABLE foo AS	
		SELECT MINHA_VARIAVEL AS CAMPO;
END;
$$;

SELECT * FROM foo;